#!/usr/bin/env ruby
#`-*- mode: ruby; -*-

$LOAD_PATH.unshift(File.expand_path("../lib", File.dirname(__FILE__)))

require 'optparse'

require 'nalloc/fusion_support/networking_manipulator'

networking_path = nil

opt_parser = OptionParser.new do |op|
  op.banner = <<-EOT
Usage: remove-fusion-adapters [opts] [adapter]+

Uninstalls a network adapter added by 'add-fusion-adapter'

Options:
EOT

  op.on("-c", "--config-path [PATH]", "Path to networking conf") do |path|
    networking_path = path
  end
end

unless Process.uid == 0
  abort "ERROR: You must be root"
end

opt_parser.parse!(ARGV)
unless ARGV.length > 0
  puts "ERROR: Incorrect number of arguments"
  puts opt_parser.help
  exit 1
end

begin
  puts "Removing adapters #{ARGV.join(', ')}"
  net_manip = Nalloc::FusionSupport::NetworkingManipulator.new(networking_path)
  net_manip.remove_adapters(ARGV.map {|adapter| Integer(adapter) })
  puts "Done. Please restart Fusion."
rescue => e
  abort "ERROR: #{e}"
end

